// This file is autogenerated, do not modify!!! 

enum LeafyThemeStyle { dark, tennojirina, kagaminerin, hatsunemiku, yuukahayase, fuukaaikiyo, sorasakihina, onikatakayoko } 

const String _dark = 'Dark'; 
const String _tennojirina = 'TennojiRina'; 
const String _kagaminerin = 'KagamineRin'; 
const String _hatsunemiku = 'HatsuneMiku'; 
const String _yuukahayase = 'YuukaHayase'; 
const String _fuukaaikiyo = 'FuukaAikiyo'; 
const String _sorasakihina = 'SorasakiHina'; 
const String _onikatakayoko = 'OnikataKayoko'; 

extension LeafyThemeStyleExtensions on LeafyThemeStyle {
  String localize() { 
    switch (this) {
      case LeafyThemeStyle.dark: 
        return _dark; 
      case LeafyThemeStyle.tennojirina: 
        return _tennojirina; 
      case LeafyThemeStyle.kagaminerin: 
        return _kagaminerin; 
      case LeafyThemeStyle.hatsunemiku: 
        return _hatsunemiku; 
      case LeafyThemeStyle.yuukahayase: 
        return _yuukahayase; 
      case LeafyThemeStyle.fuukaaikiyo: 
        return _fuukaaikiyo; 
      case LeafyThemeStyle.sorasakihina: 
        return _sorasakihina; 
      case LeafyThemeStyle.onikatakayoko: 
        return _onikatakayoko; 
      default:
        throw Exception('Unknown type'); 
    } 
  }
}

String stringifyLeafyThemeStyle(LeafyThemeStyle style) {
  switch (style) {
   case LeafyThemeStyle.dark: 
    return _dark; 
   case LeafyThemeStyle.tennojirina: 
    return _tennojirina; 
   case LeafyThemeStyle.kagaminerin: 
    return _kagaminerin; 
   case LeafyThemeStyle.hatsunemiku: 
    return _hatsunemiku; 
   case LeafyThemeStyle.yuukahayase: 
    return _yuukahayase; 
   case LeafyThemeStyle.fuukaaikiyo: 
    return _fuukaaikiyo; 
   case LeafyThemeStyle.sorasakihina: 
    return _sorasakihina; 
   case LeafyThemeStyle.onikatakayoko: 
    return _onikatakayoko; 
   default:
    throw Exception('Unknown type'); 
  }
}

LeafyThemeStyle leafyThemeStyleFromString(String str) {
  switch (str) {
   case _dark: 
    return LeafyThemeStyle.dark; 
   case _tennojirina: 
    return LeafyThemeStyle.tennojirina; 
   case _kagaminerin: 
    return LeafyThemeStyle.kagaminerin; 
   case _hatsunemiku: 
    return LeafyThemeStyle.hatsunemiku; 
   case _yuukahayase: 
    return LeafyThemeStyle.yuukahayase; 
   case _fuukaaikiyo: 
    return LeafyThemeStyle.fuukaaikiyo; 
   case _sorasakihina: 
    return LeafyThemeStyle.sorasakihina; 
   case _onikatakayoko: 
    return LeafyThemeStyle.onikatakayoko; 
   default:
    throw Exception('Unknown type'); 
  }
}
