// This file is autogenerated, do not modify!!! 

enum LeafyThemeStyle { dark, rina, kagaminerin, yuukahayase } 

const String _dark = 'Dark'; 
const String _rina = 'Rina'; 
const String _kagaminerin = 'KagamineRin'; 
const String _yuukahayase = 'YuukaHayase'; 

extension LeafyThemeStyleExtensions on LeafyThemeStyle {
  String localize() { 
    switch (this) {
      case LeafyThemeStyle.dark: 
        return _dark; 
      case LeafyThemeStyle.rina: 
        return _rina; 
      case LeafyThemeStyle.kagaminerin: 
        return _kagaminerin; 
      case LeafyThemeStyle.yuukahayase: 
        return _yuukahayase; 
      default:
        throw Exception('Unknown type'); 
    } 
  }
}

String stringifyLeafyThemeStyle(LeafyThemeStyle style) {
  switch (style) {
   case LeafyThemeStyle.dark: 
    return _dark; 
   case LeafyThemeStyle.rina: 
    return _rina; 
   case LeafyThemeStyle.kagaminerin: 
    return _kagaminerin; 
   case LeafyThemeStyle.yuukahayase: 
    return _yuukahayase; 
   default:
    throw Exception('Unknown type'); 
  }
}

LeafyThemeStyle leafyThemeStyleFromString(String str) {
  switch (str) {
   case _dark: 
    return LeafyThemeStyle.dark; 
   case _rina: 
    return LeafyThemeStyle.rina; 
   case _kagaminerin: 
    return LeafyThemeStyle.kagaminerin; 
   case _yuukahayase: 
    return LeafyThemeStyle.yuukahayase; 
   default:
    throw Exception('Unknown type'); 
  }
}
