// This file is autogenerated, do not modify!

import 'package:flutter/material.dart';

import '../../utils/enum/leafy_theme_style.dart';
import 'leafy_theme.dart';
import 'leafy_theme_constants.dart';

const Color _kDarkForegroundColor = Colors.white;

const Radius _defaultRadius = Radius.zero;

class HomeTheme extends LeafyTheme {
  const HomeTheme.dark(Widget child)
      : super(
          child: child,
          style: LeafyThemeStyle.dark,
          leafyColor: const Color(0xffC5AAC6),
          foregroundColor: const Color(0xfff5e0e9),
          foregroundPressedColor: const Color(0xffab9ca3),
          backgroundColor: const Color(0xff010001),
          secondaryBackgroundColor: const Color(0xff010001),
          textInfoColor: const Color(0xfff5e0e9),
          dialogPositiveColor: Colors.green,
          dialogNegativeColor: Colors.red,
          separatorColor: const Color(0xff54A4C4),
          deleteColor: Colors.red,
          bodyText1: const TextStyle(
            fontSize: kBodyText1FontSize,
            color: _kDarkForegroundColor,
          ),
          bodyText2: const TextStyle(
            fontSize: kBodyText2FontSize,
            color: _kDarkForegroundColor,
          ),
          bodyText3: const TextStyle(
            fontSize: kBodyText3FontSize,
            color: _kDarkForegroundColor,
          ),
          bodyText4: const TextStyle(
            fontSize: kBodyText4FontSize,
            color: _kDarkForegroundColor,
          ),
          bodyText5: const TextStyle(
            fontSize: kBodyText5FontSize,
            color: _kDarkForegroundColor,
          ),
          bodyText6: const TextStyle(
            fontSize: kBodyText6FontSize,
            color: _kDarkForegroundColor,
          ),
          defaultRadius: _defaultRadius,
        );

  const HomeTheme.rina(Widget child)
      : super(
          child: child,
          style: LeafyThemeStyle.rina,
          leafyColor: const Color(0xffEDA7D0),
          foregroundColor: const Color(0xffede0e5),
          foregroundPressedColor: const Color(0xffa59ca0),
          backgroundColor: const Color(0xff27152c),
          secondaryBackgroundColor: const Color(0xff27152c),
          textInfoColor: const Color(0xffede0e5),
          dialogPositiveColor: Colors.green,
          dialogNegativeColor: Colors.red,
          separatorColor: const Color(0xffD79CAA),
          deleteColor: Colors.red,
          bodyText1: const TextStyle(
            fontSize: kBodyText1FontSize,
            color: _kDarkForegroundColor,
          ),
          bodyText2: const TextStyle(
            fontSize: kBodyText2FontSize,
            color: _kDarkForegroundColor,
          ),
          bodyText3: const TextStyle(
            fontSize: kBodyText3FontSize,
            color: _kDarkForegroundColor,
          ),
          bodyText4: const TextStyle(
            fontSize: kBodyText4FontSize,
            color: _kDarkForegroundColor,
          ),
          bodyText5: const TextStyle(
            fontSize: kBodyText5FontSize,
            color: _kDarkForegroundColor,
          ),
          bodyText6: const TextStyle(
            fontSize: kBodyText6FontSize,
            color: _kDarkForegroundColor,
          ),
          defaultRadius: _defaultRadius,
        );

  const HomeTheme.kagaminerin(Widget child)
      : super(
          child: child,
          style: LeafyThemeStyle.kagaminerin,
          leafyColor: const Color(0xffEBDB9B),
          foregroundColor: const Color(0xffeae3e1),
          foregroundPressedColor: const Color(0xffa39e9d),
          backgroundColor: const Color(0xff493c30),
          secondaryBackgroundColor: const Color(0xff493c30),
          textInfoColor: const Color(0xffeae3e1),
          dialogPositiveColor: Colors.green,
          dialogNegativeColor: Colors.red,
          separatorColor: const Color(0xffD0BDB2),
          deleteColor: Colors.red,
          bodyText1: const TextStyle(
            fontSize: kBodyText1FontSize,
            color: _kDarkForegroundColor,
          ),
          bodyText2: const TextStyle(
            fontSize: kBodyText2FontSize,
            color: _kDarkForegroundColor,
          ),
          bodyText3: const TextStyle(
            fontSize: kBodyText3FontSize,
            color: _kDarkForegroundColor,
          ),
          bodyText4: const TextStyle(
            fontSize: kBodyText4FontSize,
            color: _kDarkForegroundColor,
          ),
          bodyText5: const TextStyle(
            fontSize: kBodyText5FontSize,
            color: _kDarkForegroundColor,
          ),
          bodyText6: const TextStyle(
            fontSize: kBodyText6FontSize,
            color: _kDarkForegroundColor,
          ),
          defaultRadius: _defaultRadius,
        );

  const HomeTheme.yuukahayase(Widget child)
      : super(
          child: child,
          style: LeafyThemeStyle.yuukahayase,
          leafyColor: const Color(0xffB0C4DD),
          foregroundColor: const Color(0xffe2e0e2),
          foregroundPressedColor: const Color(0xff9e9c9e),
          backgroundColor: const Color(0xff161518),
          secondaryBackgroundColor: const Color(0xff161518),
          textInfoColor: const Color(0xffe2e0e2),
          dialogPositiveColor: Colors.green,
          dialogNegativeColor: Colors.red,
          separatorColor: const Color(0xff92ACD7),
          deleteColor: Colors.red,
          bodyText1: const TextStyle(
            fontSize: kBodyText1FontSize,
            color: _kDarkForegroundColor,
          ),
          bodyText2: const TextStyle(
            fontSize: kBodyText2FontSize,
            color: _kDarkForegroundColor,
          ),
          bodyText3: const TextStyle(
            fontSize: kBodyText3FontSize,
            color: _kDarkForegroundColor,
          ),
          bodyText4: const TextStyle(
            fontSize: kBodyText4FontSize,
            color: _kDarkForegroundColor,
          ),
          bodyText5: const TextStyle(
            fontSize: kBodyText5FontSize,
            color: _kDarkForegroundColor,
          ),
          bodyText6: const TextStyle(
            fontSize: kBodyText6FontSize,
            color: _kDarkForegroundColor,
          ),
          defaultRadius: _defaultRadius,
        );
}
