// This file is autogenerated, do not modify!

part of 'leafy_theme.dart';

typedef ThemeCreator<S extends LeafyTheme> = S Function({
  required Widget child,
});

HomeTheme _homeCreator(Widget child) {
  switch (LeafyTheme.currentStyle) {
      case LeafyThemeStyle.dark:
          return HomeTheme.dark(child);

      case LeafyThemeStyle.mystia:
          return HomeTheme.mystia(child);

      case LeafyThemeStyle.mystiaalternative:
          return HomeTheme.mystiaalternative(child);

      case LeafyThemeStyle.tennojirina:
          return HomeTheme.tennojirina(child);

      case LeafyThemeStyle.kagaminerin:
          return HomeTheme.kagaminerin(child);

      case LeafyThemeStyle.hatsunemiku:
          return HomeTheme.hatsunemiku(child);

      case LeafyThemeStyle.yuukahayase:
          return HomeTheme.yuukahayase(child);

      case LeafyThemeStyle.fuukaaikiyo:
          return HomeTheme.fuukaaikiyo(child);

      case LeafyThemeStyle.sorasakihina:
          return HomeTheme.sorasakihina(child);

      case LeafyThemeStyle.onikatakayoko:
          return HomeTheme.onikatakayoko(child);

      case LeafyThemeStyle.suigintou:
          return HomeTheme.suigintou(child);

      case LeafyThemeStyle.suigintoualternative:
          return HomeTheme.suigintoualternative(child);

      case LeafyThemeStyle.hutao:
          return HomeTheme.hutao(child);


    default:
      throw 'Unknown style';
  }
}

final _creatorMap = {
  HomeTheme: _homeCreator,
};
