// This file is autogenerated, do not modify!

part of 'leafy_theme.dart';

typedef ThemeCreator<S extends LeafyTheme> = S Function({
  required Widget child,
});

HomeTheme _homeCreator(Widget child) {
  switch (LeafyTheme.currentStyle) {
      case LeafyThemeStyle.dark:
          return HomeTheme.dark(child);

      case LeafyThemeStyle.rina:
          return HomeTheme.rina(child);

      case LeafyThemeStyle.kagaminerin:
          return HomeTheme.kagaminerin(child);

      case LeafyThemeStyle.yuukahayase:
          return HomeTheme.yuukahayase(child);


    default:
      throw 'Unknown style';
  }
}

final _creatorMap = {
  HomeTheme: _homeCreator,
};
